[package]
name = "s2-verification"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
eyre = "0.6.12"
s2-sdk = ">=0.23.0"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
serde_json = "1.0.143"
antithesis_sdk = "0.2.6"
# required for antithesis_sdk rand compatibility
# needs to be 0.8 till it upgrades
rand = "0.8.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
